###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "userId": "jinhwan",
    "password": "qwer"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userId": "jinhwan",
    "password": "qwer",
    "email": "test1@test1.com"
}

###
PATCH http://localhost:3000/auth/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWE3MzEwYmRhNGUxOWI2OTQxY2RkNDgiLCJlbWFpbCI6InRlc3QxQHRlc3QxLmNvbSIsImlhdCI6MTcwNTQ1NjI0OCwiZXhwIjoxNzA1NTQyNjQ4fQ.Wa0VxJj0NaShwMn4v8ZVVbvW0sD5cydjNrqRypJnI94

{
    "oldPassword": "qwer",
    "newPassword": "1234"
}